In [4]:
import numpy as np
pos =11 # to correspond to number of words used in sentence in the implementation of attention function
d=4 # to correspond to the embedding dimension used in the implementation of attention function

PE=np.zeros((pos,d),dtype=np.float32)

print(PE)
print(PE.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(11, 4)


In [5]:
for i in range(pos):
    for j in range(d):
        if j%2==0:
            PE[i,j]=np.sin(i/(10000**(j/d)))
        else:
            PE[i,j]=np.cos(i/(10000**((j-1)/d)))

print(PE)

[[ 0.          1.          0.          1.        ]
 [ 0.84147096  0.5403023   0.00999983  0.99995   ]
 [ 0.9092974  -0.41614684  0.01999867  0.9998    ]
 [ 0.14112    -0.9899925   0.0299955   0.99955004]
 [-0.7568025  -0.6536436   0.03998933  0.9992001 ]
 [-0.9589243   0.2836622   0.04997917  0.99875027]
 [-0.2794155   0.96017027  0.059964    0.99820054]
 [ 0.6569866   0.75390226  0.06994285  0.997551  ]
 [ 0.98935825 -0.14550003  0.0799147   0.99680173]
 [ 0.4121185  -0.91113025  0.08987855  0.9959527 ]
 [-0.5440211  -0.8390715   0.09983341  0.9950042 ]]


That is it this is then added to embedding matrix and then rest of the attention step follow. 