In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
import torch

# Explicitly load the configuration first to ensure all parameters, including rope_scaling,
# are correctly parsed before passing to the model.
config = AutoConfig.from_pretrained("microsoft/Phi-3-mini-4k-instruct", trust_remote_code=True)

# Fix for KeyError: 'type' when rope_scaling is null in config.json but loaded as an invalid dict.
# Ensure config.rope_scaling is None if it's a dictionary that doesn't contain the 'type' key.
# This handles cases where 'null' is interpreted as an empty dict or an incomplete one.
if isinstance(config.rope_scaling, dict) and "type" not in config.rope_scaling:
    config.rope_scaling = None

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    config=config, # Pass the pre-loaded configuration
    device_map = "cuda",
    torch_dtype="auto",
    trust_remote_code=True,
)

tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

configuration_phi3.py:   0%|          | 0.00/11.2k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_phi3.py:   0%|          | 0.00/73.2k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

Reconstructing (incomplete total...): |          |  0.00B /  0.00B            

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB            

tokenizer.model: downloading bytes:           |  0.00B            

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [ ]:
prompt = "write an email to manager requesting for work from home."

#tokenizing prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

#generate text
generation_output = model.generate(
    input_ids = input_ids,
    max_new_tokens = 25,
    use_cache=False
)

print(tokenizer.decode(generation_output[0]))

/usr/local/lib/python3.13/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.13/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.13/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API 

write an email to manager requesting for work from home.

Dear [Manager's Name],

I hope this email finds you well. I am writing to request


In [ ]:
print(input_ids) #this went into the model. tokenizer processed input and returned info that model needs.

tensor([[ 2436,   385,  4876,   304,  8455,  2009,   292,   363,   664,   515,
          3271, 29889]], device='cuda:0')


these id values are actually token ids , they point to token id table , that has all the tokens that this tokenizer know.

In [ ]:
#to see the words we can decode

for id in input_ids[0]:
  print(tokenizer.decode(id))

write
an
email
to
manager
request
ing
for
work
from
home
.


In [ ]:
#lets see ouput token ids
print(generation_output)

tensor([[ 2436,   385,  4876,   304,  8455,  2009,   292,   363,   664,   515,
          3271, 29889,    13,    13, 29928,   799,   518,  3260, 29915, 29879,
          4408,  1402,    13,    13, 29902,  4966,   445,  4876, 14061,   366,
          1532, 29889,   306,   626,  5007,   304,  2009]], device='cuda:0')


it has both input and output token

In [ ]:
for out in generation_output:
  print(tokenizer.decode(out))

write an email to manager requesting for work from home.

Dear [Manager's Name],

I hope this email finds you well. I am writing to request


creating better token embeddings

In [ ]:
from transformers import AutoModel, AutoTokenizer

#load tokenizer
tokenizer=AutoTokenizer.from_pretrained("microsoft/deberta-base")

#load model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

#tokenize
tokens = tokenizer("Computer science is fun", return_tensors="pt")

#process token
output = model(**tokens)[0]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  241MB            

pytorch_model.bin: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2Model LOAD REPORT from: microsoft/deberta-v3-xsmall
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
mask_predictions.classifier.weight         | UNEXPECTED |  | 
mask_predictions.LayerNorm.bias            | UNEXPECTED |  | 
lm_predictions.lm_head.bias                | UNEXPECTED |  | 
lm_predictions.lm_head.dense.bias          | UNEXPECTED |  | 
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |  | 
lm_predictions.lm_head.dense.weight        | UNEXPECTED |  | 
mask_predictions.classifier.bias           | UNEXPECTED |  | 
mask_predictions.dense.weight              | UNEXPECTED |  | 
deberta.embeddings.word_embeddings._weight | UNEXPECTED |  | 
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |  | 
mask_predictions.LayerNorm.weight          | UNEXPECTED |  | 
mask_predictions.dense.bias                | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from d

model.safetensors: reconstructing file:   0%|          |  0.00B /  241MB            

model.safetensors: downloading bytes:           |  0.00B            

In [ ]:
output.shape

torch.Size([1, 6, 384])

In [ ]:
for token in tokens['input_ids'][0]:
  print(tokenizer.decode(token))

[CLS]
Computer
 science
 is
 fun
[SEP]


In [ ]:
print(output)

tensor([[[-3.4883,  0.0165, -0.1897,  ..., -0.0155, -0.3992, -0.0757],
         [-0.6138,  0.3276,  0.1354,  ..., -0.1176, -0.5474, -0.6968],
         [-0.7446,  0.1802,  0.2695,  ...,  0.9346,  0.0101,  0.3799],
         [ 0.1171,  0.3462, -0.3801,  ...,  0.8960,  0.0739,  1.4932],
         [-0.5615,  0.2659,  0.4534,  ..., -0.4167, -0.0843, -1.6709],
         [-3.2109,  0.0737, -0.3042,  ...,  0.1943, -0.5513, -0.1107]]],
       dtype=torch.float16, grad_fn=<NativeLayerNormBackward0>)


now, in the above example we see each row a vector embedding for each token, but what we use now mostly actually represent sentences , paragraphs as single vector. lets see:

In [ ]:
from sentence_transformers import SentenceTransformer

#load model
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

#encode sentences
vector = model.encode("Ai is the most intresting domain in computer science")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
vector.shape # we see a single row for entore sentence with dimension 768.

(768,)

In [ ]:
#what if a text file
vector = model.encode("Harry potter will always be one of the finest fanstasy ever written. though the book revolves around childer, harry is just 11 when the book starts, the series take you through a journey and you cant stop being bewitched by every amazing charcter, various themes. ofcourse the magic and adventure makes it fun but what mkes it great is i think the sheer use of human imagination to create a new world and yet making it so relatable to every single ordinary individual.")
vector.shape

(768,)

Using pre-trained word embeddings:

In [ ]:
!pip install gensim
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-50")

model.most_similar([model['book']], topn=10)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 21.7 MB/s eta 0:00:00
[==================================================] 100.0% 66.0/66.0MB downloaded


[('book', 0.9999998807907104),
 ('books', 0.9047631025314331),
 ('story', 0.8662747144699097),
 ('novel', 0.8550738096237183),
 ('writing', 0.843974232673645),
 ('published', 0.8439115881919861),
 ('biography', 0.8398316502571106),
 ('author', 0.8371228575706482),
 ('wrote', 0.8293616771697998),
 ('written', 0.8216683864593506)]